# vim:syntax=make:

.include "${.CURDIR}/drivers/1w/Makefile.inc"
.include "${.CURDIR}/drivers/gpio/Makefile.inc"
.include "${.CURDIR}/drivers/i2c/Makefile.inc"
.include "${.CURDIR}/drivers/misc/Makefile.inc"
.include "${.CURDIR}/drivers/serial/Makefile.inc"
#.include "${.CURDIR}/drivers/spi/Makefile.inc"
