# vim:syntax=make:

.PATH: ${LIBC_SRCTOP}/ctype

SRCS+=	ctype_.c \
	isalnum.c \
	isalpha.c \
	isascii.c \
	isblank.c \
	iscntrl.c \
	isdigit.c \
	islower.c \
	isprint.c \
	ispunct.c \
	isspace.c \
	isupper.c \
	iswalnum.c \
	iswalpha.c \
	iswblank.c \
	iswcntrl.c \
	iswctype.c \
	iswdigit.c \
	iswgraph.c \
	iswlower.c \
	iswprint.c \
	iswpunct.c \
	iswspace.c \
	iswupper.c \
	iswxdigit.c \
	isxdigit.c \
	jp2uc.c \
	toascii.c \
	tolower.c \
	toupper.c \
	towctrans.c \
	towlower.c \
	towupper.c \
	wctrans.c \
	wctype.c
