/* Default to 128kB heap */
//#define HEAP_SIZE	(128 * 1024)
#define MAX_DYNAMIC_THREADS	10

#define THREAD_IDLE_PRIORITY	7
#define THREAD_MAX_PRIORITY		0
#define THREAD_MIN_PRIORITY		7
#define CHAOS_SCHED_TICK		10
