# vim:syntax=make:

.PATH: ${LIBC_SRCTOP}/reent

SRCS+=	closer.c \
	execr.c \
	fcntlr.c \
	fstat64r.c \
	fstatr.c \
	getreent.c \
	gettimeofdayr.c \
	impure.c \
	isattyr.c \
	linkr.c \
	lseek64r.c \
	lseekr.c \
	mkdirr.c \
	open64r.c \
	openr.c \
	readr.c \
	reent.c \
	renamer.c \
	sbrkr.c \
	signalr.c \
	signgam.c \
	stat64r.c \
	statr.c \
	timesr.c \
	unlinkr.c \
	writer.c
